// subworkflows/functional_annotation/main.nf

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT MODULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
// Note the path points to your local module found with ls -R
include { PICRUST } from '../../modules/local/picrust'

workflow FUNCTIONAL_ANNOTATION {

    take:
    ch_asv_table // channel: [ val(meta), path(asv_table) ]

    main:
    ch_versions = channel.empty()

    //
    // MODULE: Run PICRUSt2
    //
    // This expects the ASV table generated by the Taxonomic Profiling subworkflow
    PICRUST(ch_asv_table)
    ch_versions = ch_versions.mix(PICRUST.out.versions)

    emit:
    pathway_abundance = PICRUST.out.pathway_abundance
    versions          = ch_versions
}